spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
    port: 9090
  datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:${spring.h2.port}/mem:testdb;
    username: sa
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

feign:
  auth-client:
    url: http://localhost:8082
