### 사용자 access token 발급
POST {{auth-app}}/oauth/token?grant_type=password&username=system&password=asdfasdf1234&scope=read&force=true
Authorization: Basic bGFvbnplbmFtb29uX2NsaWVudF9pZDpsYW9uemVuYW1vb25fY2xpZW50X3NlY3JldA==

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("ACCESS_TOKEN", response.body.access_token);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_ORIGIN",
  "parentId": {{BOARD_ID}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_ORIGIN", response.body.data.boardId);
%}

### 게시글 생성 성공 > 댓글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_REPLY",
  "parentId": {{BOARD_ID_FOR_REPLY_FOR_ORIGIN}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_REPLY", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_ORIGIN",
  "parentId": {{BOARD_ID}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_ORIGIN", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_ORIGIN",
  "parentId": {{BOARD_ID}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_ORIGIN", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_ORIGIN",
  "parentId": {{BOARD_ID}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_ORIGIN", response.body.data.boardId);
%}

### 게시글 생성 성공 > 댓글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_REPLY",
  "parentId": {{BOARD_ID_FOR_REPLY_FOR_ORIGIN}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_REPLY", response.body.data.boardId);
%}

### 게시글 생성 성공 > 댓글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_REPLY",
  "parentId": {{BOARD_ID_FOR_REPLY_FOR_ORIGIN}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_REPLY", response.body.data.boardId);
%}

### 게시글 생성 성공 > 댓글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_REPLY",
  "parentId": {{BOARD_ID_FOR_REPLY_FOR_ORIGIN}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_REPLY", response.body.data.boardId);
%}

### 게시글 생성 성공 > 댓글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_REPLY",
  "parentId": {{BOARD_ID_FOR_REPLY_FOR_ORIGIN}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_REPLY", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_ORIGIN",
  "parentId": {{BOARD_ID}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_ORIGIN", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글에 대한 댓글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "hierarchyType": "REPLY_FOR_ORIGIN",
  "parentId": {{BOARD_ID}},
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID_FOR_REPLY_FOR_ORIGIN", response.body.data.boardId);
%}

### 게시글 생성 성공 > 원글
POST {{service-app}}/boards
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 수정
PUT {{service-app}}/boards/{{BOARD_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "boardType": "ALL",
  "contentType": "GENERAL",
  "title": "첫번째 게시글",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
client.global.set("BOARD_ID", response.body.data.boardId);
%}

### 게시글 상세 조회
GET {{service-app}}/boards/{{BOARD_ID}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
%}

### 게시글 삭제
DELETE {{service-app}}/boards/{{BOARD_ID}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
%}

### 게시글 목록 조회(페이징)
GET {{service-app}}/boards?pageSort=title:asc,id:desc

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is wrong");
});
%}
