feign:
  client:
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 10000
        readTimeout: 20000
  slack-client:
    url: none

logging:
  level:
    me.lozm.slack.client.SlackClient: DEBUG